files:
  Access8Math.po: 336
  Access8Math.pot: 336
  Access8Math.xliff: 338
  BMI.po: 300
  BMI.pot: 300
  BMI.xliff: 302
  MSEdgeDiscardAnnouncements.po: 372
  MSEdgeDiscardAnnouncements.pot: 372
  MSEdgeDiscardAnnouncements.xliff: 374
  SentenceNav.po: 360
  SentenceNav.pot: 360
  SentenceNav.xliff: 362
  beepKeyboard.po: 408
  beepKeyboard.pot: 408
  beepKeyboard.xliff: 410
  charInfo.po: 296
  charInfo.pot: 296
  charInfo.xliff: 298
  clipContentsDesigner.po: 256
  clipContentsDesigner.pot: 256
  clipContentsDesigner.xliff: 258
  clock.po: 454
  clock.pot: 454
  clock.xliff: 452
  columnsReview.po: 332
  columnsReview.pot: 332
  columnsReview.xliff: 334
  controlUsageAssistant.po: 260
  controlUsageAssistant.pot: 260
  controlUsageAssistant.xliff: 262
  cursorLocator.po: 224
  cursorLocator.pot: 224
  cursorLocator.xliff: 436
  customNotifications.po: 244
  customNotifications.pot: 244
  customNotifications.xliff: 268
  dayOfTheWeek.po: 376
  dayOfTheWeek.pot: 376
  dayOfTheWeek.xliff: 378
  debugHelper.po: 428
  debugHelper.pot: 428
  debugHelper.xliff: 430
  dropbox.po: 416
  dropbox.pot: 416
  dropbox.xliff: 418
  eMule.po: 194
  eMule.pot: 194
  eMule.xliff: 264
  easyTableNavigator.po: 312
  easyTableNavigator.pot: 312
  easyTableNavigator.xliff: 314
  emoticons.po: 176
  emoticons.pot: 176
  emoticons.xliff: 178
  enhancedAnnotations.po: 252
  enhancedAnnotations.pot: 252
  enhancedAnnotations.xliff: 266
  enhancedTouchGestures.po: 210
  enhancedTouchGestures.pot: 210
  enhancedTouchGestures.xliff: 286
  evtTracker.po: 438
  evtTracker.pot: 438
  evtTracker.xliff: 440
  goldenCursor.po: 368
  goldenCursor.pot: 368
  goldenCursor.xliff: 370
  goldwave.po: 180
  goldwave.pot: 180
  goldwave.xliff: 182
  inputLock.po: 424
  inputLock.pot: 424
  inputLock.xliff: 426
  instantTranslate.po: 324
  instantTranslate.pot: 324
  instantTranslate.xliff: 326
  mp3DirectCut.po: 404
  mp3DirectCut.pot: 404
  mp3DirectCut.xliff: 406
  numpadNavMode.po: 412
  numpadNavMode.pot: 412
  numpadNavMode.xliff: 414
  nvdaDevTestToolbox.po: 308
  nvdaDevTestToolbox.pot: 308
  nvdaDevTestToolbox.xliff: 310
  objPad.po: 356
  objPad.pot: 356
  objPad.xliff: 358
  objWatcher.po: 400
  objWatcher.pot: 400
  objWatcher.xliff: 402
  outlookExtended.po: 380
  outlookExtended.pot: 380
  outlookExtended.xliff: 382
  pcKbBrl.po: 228
  pcKbBrl.pot: 228
  pcKbBrl.xliff: 276
  proxy.po: 384
  proxy.pot: 384
  proxy.xliff: 386
  rdAccess.po: 288
  rdAccess.pot: 288
  rdAccess.xliff: 290
  readFeeds.md: 450
  readFeeds.po: 232
  readFeeds.pot: 232
  readFeeds.xliff: 278
  readonlyProfiles.xliff: 270
  reportSymbols.po: 236
  reportSymbols.pot: 236
  reportSymbols.xliff: 274
  resourceMonitor.po: 214
  resourceMonitor.pot: 214
  resourceMonitor.xliff: 284
  reviewCursorCopier.po: 420
  reviewCursorCopier.pot: 420
  reviewCursorCopier.xliff: 422
  robEnhancements.po: 396
  robEnhancements.pot: 396
  robEnhancements.xliff: 398
  sayCurrentKeyboardLanguage.po: 392
  sayCurrentKeyboardLanguage.pot: 392
  sayCurrentKeyboardLanguage.xliff: 394
  sayProductNameAndVersion.po: 352
  sayProductNameAndVersion.pot: 352
  sayProductNameAndVersion.xliff: 354
  searchWith.po: 388
  searchWith.pot: 388
  searchWith.xliff: 390
  speechLogger.po: 348
  speechLogger.pot: 348
  speechLogger.xliff: 350
  stationPlaylist.po: 218
  stationPlaylist.pot: 218
  stationPlaylist.xliff: 282
  systrayList.po: 340
  systrayList.pot: 340
  systrayList.xliff: 342
  tonysEnhancements.po: 304
  tonysEnhancements.pot: 304
  tonysEnhancements.xliff: 306
  translateNvdaAddonsWithCrowdin.md: 448
  translateNvdaAddonsWithCrowdin.po: 446
  translateNvdaAddonsWithCrowdin.pot: 446
  unicodeBrailleInput.po: 328
  unicodeBrailleInput.pot: 328
  unicodeBrailleInput.xliff: 330
  updateChannel.po: 320
  updateChannel.pot: 320
  updateChannel.xliff: 322
  urlShortener.po: 240
  urlShortener.pot: 240
  urlShortener.xliff: 272
  virtualRevision.po: 432
  virtualRevision.pot: 432
  virtualRevision.xliff: 434
  winMag.po: 292
  winMag.pot: 292
  winMag.xliff: 294
  winWizard.po: 344
  winWizard.pot: 344
  winWizard.xliff: 346
  wordNav.po: 364
  wordNav.pot: 364
  wordNav.xliff: 366
projectId: 780748
