files:
  Access8Math.po: 336
  Access8Math.pot: 336
  Access8Math.xliff: 338
  BMI.po: 300
  BMI.pot: 300
  BMI.xliff: 302
  BrailleExtender.po: 592
  BrailleExtender.pot: 592
  IndentNav.po: 578
  IndentNav.pot: 578
  MSEdgeDiscardAnnouncements.po: 372
  MSEdgeDiscardAnnouncements.pot: 372
  MSEdgeDiscardAnnouncements.xliff: 374
  SentenceNav.po: 360
  SentenceNav.pot: 360
  SentenceNav.xliff: 362
  TeleNVDA.po: 588
  TeleNVDA.pot: 588
  TeleNVDA.xliff: 616
  VLC.po: 582
  VLC.pot: 582
  askOpenRouter.po: 458
  askOpenRouter.pot: 458
  askOpenRouter.xliff: 456
  beepKeyboard.po: 408
  beepKeyboard.pot: 408
  beepKeyboard.xliff: 410
  brailleEssentials.po: 627
  brailleEssentials.pot: 627
  calibre.po: 586
  calibre.pot: 586
  charInfo.po: 296
  charInfo.pot: 296
  charInfo.xliff: 298
  clipContentsDesigner.po: 256
  clipContentsDesigner.pot: 256
  clipContentsDesigner.xliff: 258
  clock.po: 454
  clock.pot: 454
  clock.xliff: 452
  columnsReview.po: 332
  columnsReview.pot: 332
  columnsReview.xliff: 334
  contactsManager.po: 645
  contactsManager.pot: 645
  contactsManager.xliff: 647
  controlUsageAssistant.po: 260
  controlUsageAssistant.pot: 260
  controlUsageAssistant.xliff: 262
  cursorLocator.po: 224
  cursorLocator.pot: 224
  cursorLocator.xliff: 436
  customBrowseMode.po: 629
  customBrowseMode.pot: 629
  customBrowseMode.xliff: 631
  customNotifications.po: 244
  customNotifications.pot: 244
  customNotifications.xliff: 268
  dayOfTheWeek.po: 376
  dayOfTheWeek.pot: 376
  dayOfTheWeek.xliff: 378
  debugHelper.po: 428
  debugHelper.pot: 428
  debugHelper.xliff: 430
  dengjen_neural_voices.po: 661
  dengjen_neural_voices.pot: 661
  dotPad.po: 663
  dotPad.pot: 663
  dotPad.xliff: 665
  dropbox.po: 416
  dropbox.pot: 416
  dropbox.xliff: 418
  eMule.po: 194
  eMule.pot: 194
  eMule.xliff: 264
  easyTableNavigator.po: 312
  easyTableNavigator.pot: 312
  easyTableNavigator.xliff: 314
  emoticons.po: 176
  emoticons.pot: 176
  emoticons.xliff: 178
  enhancedAnnotations.po: 252
  enhancedAnnotations.pot: 252
  enhancedAnnotations.xliff: 266
  enhancedTouchGestures.po: 210
  enhancedTouchGestures.pot: 210
  enhancedTouchGestures.xliff: 286
  evtTracker.po: 438
  evtTracker.pot: 438
  evtTracker.xliff: 440
  favoriteLinks.po: 643
  favoriteLinks.pot: 643
  favoriteLinks.xliff: 637
  goldenCursor.po: 368
  goldenCursor.pot: 368
  goldenCursor.xliff: 370
  goldwave.po: 180
  goldwave.pot: 180
  goldwave.xliff: 182
  inputLock.po: 424
  inputLock.pot: 424
  inputLock.xliff: 426
  instantTranslate.po: 324
  instantTranslate.pot: 324
  instantTranslate.xliff: 326
  mp3DirectCut.po: 404
  mp3DirectCut.pot: 404
  mp3DirectCut.xliff: 406
  noBeepsSpeechMode.po: 570
  noBeepsSpeechMode.pot: 570
  noBeepsSpeechMode.xliff: 602
  notepadMarkdownBrowseMode.po: 659
  notepadMarkdownBrowseMode.pot: 659
  notepadMarkdownBrowseMode.xliff: 657
  numpadNavMode.po: 412
  numpadNavMode.pot: 412
  numpadNavMode.xliff: 414
  nvdaDevTestToolbox.po: 308
  nvdaDevTestToolbox.pot: 308
  nvdaDevTestToolbox.xliff: 310
  objPad.po: 356
  objPad.pot: 356
  objPad.xliff: 358
  objWatcher.po: 400
  objWatcher.pot: 400
  objWatcher.xliff: 402
  outlookExtended.po: 380
  outlookExtended.pot: 380
  outlookExtended.xliff: 382
  pcKbBrl.po: 228
  pcKbBrl.pot: 228
  pcKbBrl.xliff: 276
  perky.po: 633
  perky.pot: 633
  perky.xliff: 635
  placeMarkers.po: 576
  placeMarkers.pot: 576
  placeMarkers.xliff: 610
  proxy.po: 384
  proxy.pot: 384
  proxy.xliff: 386
  rdAccess.po: 288
  rdAccess.pot: 288
  rdAccess.xliff: 290
  readFeeds.po: 232
  readFeeds.pot: 232
  readFeeds.xliff: 278
  readonlyProfiles.po: 618
  readonlyProfiles.pot: 618
  readonlyProfiles.xliff: 270
  reportSymbols.po: 236
  reportSymbols.pot: 236
  reportSymbols.xliff: 274
  resourceMonitor.po: 214
  resourceMonitor.pot: 214
  resourceMonitor.xliff: 284
  reviewCursorCopier.po: 420
  reviewCursorCopier.pot: 420
  reviewCursorCopier.xliff: 422
  robEnhancements.po: 396
  robEnhancements.pot: 396
  robEnhancements.xliff: 398
  sayCurrentKeyboardLanguage.po: 392
  sayCurrentKeyboardLanguage.pot: 392
  sayCurrentKeyboardLanguage.xliff: 394
  sayProductNameAndVersion.po: 352
  sayProductNameAndVersion.pot: 352
  sayProductNameAndVersion.xliff: 354
  searchWith.po: 388
  searchWith.pot: 388
  searchWith.xliff: 390
  showSelectionWhenBrailleTetheredToReview.po: 568
  showSelectionWhenBrailleTetheredToReview.pot: 568
  showSelectionWhenBrailleTetheredToReview.xliff: 600
  soundSplitter.po: 584
  soundSplitter.pot: 584
  soundSplitter.xliff: 614
  speechLogger.po: 348
  speechLogger.pot: 348
  speechLogger.xliff: 350
  stationPlaylist.po: 218
  stationPlaylist.pot: 218
  stationPlaylist.xliff: 282
  systrayList.po: 340
  systrayList.pot: 340
  systrayList.xliff: 342
  terminalAccess.po: 590
  terminalAccess.pot: 590
  thunderbirdPlus.po: 572
  thunderbirdPlus.pot: 572
  thunderbirdPlus.xliff: 604
  toneMaster.po: 574
  toneMaster.pot: 574
  toneMaster.xliff: 608
  tonysEnhancements.po: 304
  tonysEnhancements.pot: 304
  tonysEnhancements.xliff: 306
  toolbarsExplorer.po: 580
  toolbarsExplorer.pot: 580
  toolbarsExplorer.xliff: 612
  trainingKeyboardCommands.xliff: 606
  translateNvdaAddonsWithCrowdin.po: 446
  translateNvdaAddonsWithCrowdin.pot: 446
  unicodeBrailleInput.po: 328
  unicodeBrailleInput.pot: 328
  unicodeBrailleInput.xliff: 330
  updateChannel.po: 320
  updateChannel.pot: 320
  updateChannel.xliff: 322
  urlShortener.po: 240
  urlShortener.pot: 240
  urlShortener.xliff: 272
  virtualRevision.po: 432
  virtualRevision.pot: 432
  virtualRevision.xliff: 434
  winMag.po: 292
  winMag.pot: 292
  winMag.xliff: 294
  winWizard.po: 344
  winWizard.pot: 344
  winWizard.xliff: 346
  windowState.po: 653
  windowState.pot: 653
  windowState.xliff: 655
  wintenApps.po: 639
  wintenApps.pot: 639
  wintenApps.xliff: 641
  wordNav.po: 364
  wordNav.pot: 364
  wordNav.xliff: 366
  wordPredictor.po: 649
  wordPredictor.pot: 649
  wordPredictor.xliff: 651
  zoomEnhancements.po: 623
  zoomEnhancements.pot: 623
  zoomEnhancements.xliff: 625
projectId: 780748
