name: automatic-release

on:
  push:
    branches: [main]

jobs:

  build:
    uses: ./.github/workflows/buildExecutable.yaml

  pre-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Download artifact
      uses: actions/download-artifact@v8
      with:
        name: l10nUtil
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: l10nUtil.exe
        name: Development build
        tag_name: dev-${{ github.run_number }}
        make_latest: true