name: automatic-release

on:
  push:
    branches: [main]

jobs:

  build:
    uses: ./.github/workflows/buildExecutable.yaml

  Automatic-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Download artifact
      uses: actions/download-artifact@v8
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: l10nUtil.exe
        name: Development build
        allowUpdates: true
        commit: ${{ github.sha }}
        replacesArtifacts: true
        tag: dev-${{ github.run_number }}
        make_latest: true