name: Build executable
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: Build executable
        run: |
          uv run pip install .
          uv run pyinstaller l10nUtil.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: l10nUtil
          path: dist/l10nUtil.exe
          archive: false

